executable = run_data_generation.sh

# il faut modifier start_index et amount_per_worker dans le fichier .sh

arguments = \
  $(Process) \
  --directory data_7 \
  --n-samples 1 \
  --n-points 10000 \
  --use-imperfections True
# ne pas oublier imperfection si je les veux

# PAS OUBLIER DE MODIFIER START_INDEX ET AMOOUNT_PER_WORKER DANS .SH

output = logs/out.$(CLUSTER).$(PROCESS)
error  = logs/err.$(CLUSTER).$(PROCESS)
log    = logs/log.$(CLUSTER).$(PROCESS)

request_cpus = 1
request_memory = 1300
+MaxRuntime = 86300
# 64800

queue 100
