executable = run_training.sh

arguments = \
  --training-id 30 \
  --data-dir data_3 \
  --max-files 400 \
  --device cpu \
  --run-diagnostics \
  --n-diagnostic-files 5

output = logs/out.$(CLUSTER).$(PROCESS)
error  = logs/err.$(CLUSTER).$(PROCESS)
log    = logs/log.$(CLUSTER).$(PROCESS)

request_cpus   = 16 
# 32
request_memory = 48000 
# 64000

+MaxRuntime = 43200   
# 12h # 28800   # 8h

queue
